site_name: MkDocs Placeholder Plugin
repo_url: https://github.com/six-two/mkdocs-placeholder-plugin
repo_name: mkdocs-placeholder-plugin

theme:
  name: material
  # name: mkdocs
  # name: readthedocs
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  features:
  - navigation.sections
  - content.code.copy
  - navigation.footer
  # For testing issue 7
  - navigation.instant

plugins:
- search
- languagetool:
    async_threads: 10
# - languagetool

markdown_extensions:
  # Message/error/warning boxes
  - admonition
  - pymdownx.details
  # Different formatting options
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  # For search exclusion
  - attr_list
  # For mermaid diagrams
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # for tabs
  - pymdownx.tabbed:
      alternate_style: true
